[shell]
font_family = "Pragmasevka Nerd Font"
time_format = "{:%H:%M}"
date_format = "%A, %x"
settings_show_advanced = true
middle_click_opens_widget_settings = false

[shell.animation]
enabled = true
speed = 1.0

[shell.panel]
transparency_mode = "solid"
borders = true
launcher_placement = "centered"
control_center_placement = "attached"

[theme]
mode = "dark"
source = "builtin"
builtin = "Dracula"

[wallpaper]
enabled = false

[notification]
enable_daemon = true
show_app_name = true
show_actions = false
layer = "top"
scale = 1.0
background_opacity = 0.95
offset_x = 20
offset_y = 8

[osd]
position = "top_right"
orientation = "horizontal"
scale = 1.0
background_opacity = 0.95
offset_x = 20
offset_y = 8

[osd.kinds]
volume = true
brightness = true
wifi = true
bluetooth = true
lock_keys = true
keyboard_layout = true

[system.monitor]
enabled = true

[weather]
enabled = false

[audio]
enable_overdrive = false

[brightness]
enable_ddcutil = false

[nightlight]
enabled = true

[location]
auto_locate = false

[bar.main]
position = "top"
thickness = 36
background_opacity = 0.92
radius = 12
margin_h = 8
margin_v = 4
padding = 6
widget_spacing = 4
scale = 1.0
shadow = true
auto_hide = false
reserve_space = true
capsule = true
capsule_radius = 6.0
capsule_opacity = 0.5

start = ["active_window", "media"]
center = ["workspaces", "sysmon"]
end = ["tray", "notifications", "network", "bluetooth", "battery", "volume", "brightness", "nightlight", "clock", "control-center"]

[plugins]
enabled = ["noctalia/bongocat", "noctalia/timer"]

[[plugins.source]]
name = "official"
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
enabled = true

[[plugins.source]]
name = "community"
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
enabled = true

[widget.workspaces]
display_mode = "id"
labels_only_when_occupied = false
hide_when_empty = false
pill_scale = 1.0
minimal = false

[widget.clock]
format = "{:%H:%M}"
tooltip_format = "{:%A, %B %d, %Y}"

[widget.media]
hide_when_no_media = true
max_width = 120

[widget.notifications]
hide_when_no_unread = true

[widget.volume]
show_label = true
device = "output"

[widget.network]
show_label = false

[widget.battery]
show_label = false
hide_when_plugged = true
hide_when_full = true

[widget.bluetooth]
show_label = false
hide_when_no_connected_device = true

[widget.brightness]
show_label = false

[widget.nightlight]
show_label = false

[widget.active_window]
type = "active_window"
max_length = 260
min_length = 80
display = "icon_and_text"
show_empty_label = false

[widget.sysmon]
type = "sysmon"
stat = "cpu_usage"
display = "graph"
show_label = false

[widget.control-center]
type = "control-center"
glyph = "noctalia"
